#!/bin/bash

mvn clean
mvn package -Drelease -DskipTests -DskipDocs
sudo rm -Rf /opt/yamcs
sudo mkdir /opt/yamcs
sudo tar -xvzf distribution/target/yamcs-5.5.0-SNAPSHOT-linux-x86_64.tar.gz --strip-components=1 -C "/opt/yamcs"

